package by.epam.dmitriysedin.finaltask.controller.command;

public enum CommandName {
	
	AUTHORIZATION, 
	GOTOLOGINPAGE, 
	CHANGELOCALE, 
	GOTOREGISTRATIONPAGE, 
	REGISTRATION, 
	ADDNEWMOVIE, 
	GOTOADDNEWMOVIE,
	SHOWALLMOVIES,
	SHOWNEXTPAGE,
	SHOWPREVIOUSPAGE,
	GOTOSHOWALLMOVIESPAGECOMMAND,
	CONCRETEMOVIEINFO,
	GOTOADDNEWRATE,
	ADDNEWRATE,
	GOTOSHOWCONCRETEMOVIEINFOPAGECOMMAND,
	LOGOUTCOMMAND,
	NOSUCHCOMMAND
	
}
